### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by a-n-g-i-e-r-i** [sbweins/budget-react-app#1]
Please review the comments associated with this issue and refactor your code accordingly. Thanks!

**Comment by a-n-g-i-e-r-i** [comment]
Make sure to include a link to your deployed Netlify API in your README.md

**Comment by a-n-g-i-e-r-i** [comment]
Nice component JSX implementation!

**Comment by sbweins** [comment]
Thanks! Updated ReadME.md with Netlify API Link!
